### ISSUE TITLE
Mała karta

### ISSUE THREAD

**Issue by 0xtrzy** [jakubfi/em400#15]
Czy rozważano zbudowanie wersji mikro np. jak ta https://hackaday.io/project/169140-blinkencard-pocket-altair-8800
Albo wykonanie płyty przedniej jak https://hackaday.io/project/8069-pidp-11 

https://cdn.hackaday.io/images/9567791526231674794.png

**Comment by jakubfi** [comment]
Tak, reimplementacja MERY-400 w takiej postaci jest rozważana. Nie spodziewałbym się jej natomiast w najbliższym czasie. :-)

**Comment by fab1an2** [comment]
Pytanie dotyczyło dwóch pomysłów. Który z nich jest 'w tej postaci' ?
Czy zaczynamy od emulatora i panelu 1:1 czy wersja zintegrowana ale mała?

Gdzie można było by dołożyć się lub po porstu kupić taki gotowy produkt? Ja bym celowal w miniaturę w skali 1:3 albo mniejsze po prostu z maliną i obudową z drewna.

**Comment by jakubfi** [comment]
Rozważany pomysł to MERA-400 w fpga + emulacja urządzeń zewnętrznych na Raspberry Pi (lub podobnym) + replika pulpitu technicznego.

Na tym etapie to tylko pomysł, nie ma urządzenia, które można by zakupić. Nie ma też planów "zrzutki" na takie urządzenie.

**Comment by wir19** [comment]
Co musiało by się stać by taka zrzutka była możliwa? Jaki byłby orientacyjny koszt takiej wersji emulowanej?
(Zazwyczaj w zależności od ilości chętnych zwiększa się zakres sprzętu).

Mera dobrze nadawała się na system czasu 'prawie rzeczywistego' może warto było by po prostu rozważyć jakieś rozwiązanie sprzętowe? Sterowanie czymś lub nawet zwykły czujnik temperatury, wilgotności i ilości światła za oknem. Chodzi o to by taki sprzęt był też użyteczny. Czy są plany podłączenia **mera400** do internetu? Jako urządzenie zewnętrzne lub jako dodatkowy dysk?

**Comment by jakubfi** [comment]
> Co musiało by się stać by taka zrzutka była możliwa?
Ktoś musiałby znaleźć czas, żeby się za to zabrać. :-)

**Comment by wir19** [comment]
Ile tego czasu musiało by być?
Powiedzmy 3000 plusów na wykopie, albo Ileś tam wpłat, albo ileś zamówień albo ileś petycji?

Prosze rozważyć. Wiele osób np. ogląda YT. Może to za mało, ale może to jest jakis bodziec. Ponawiam pytanie. Co musiało by się stać?

**Comment by 0xtrzy** [comment]
aha
