### ISSUE TITLE
Wiki i pytania

### ISSUE THREAD

**Issue by fab1an2** [jakubfi/em400#16]
Mam mnóstwo pytań do wiki i nie mam jak ich zadać.
Najlepiej było by gdyby sekcja **dyskusja** w każdej stronie była po prostu dostępna dla zwyklego użytkownika.
Wtedy każdy kto znajdzie błąd może po prostu napisac w **dyskusji** informację.

Przykład
_https://mera400.pl/EMAS na końcu jest link do listy rozkazów, który wskazuje na stronę która nie istnieje a która jest https://mera400.pl/Lista_rozkaz%C3%B3w tutaj._

Jako alternatywa może dodac po prostu gdzieś **email** do zgłaszania pytań. System akceptacji w wiki i ew. sprawdzania historii skutecznie pozwoliłby na ogarnięcie ew. spamu.

Brakuje mi informacji o priorytetach dyrektyw assemblera, czy przełączniki z linii poleceń sa wazniejsze niż np. .cpu ? Nie znalazłem informacji o formacie plików. Ile bitów, jak się kończą jaki zestaw znaków sterujących obsługują, czy maja jakies kodowanie polskich znaków lub jak kiedyś pamiętam przy drukowaniu rachunków drukarka wierszowa drukowała polskie znaki za pomoca cedyli i slasza

**Comment by jakubfi** [comment]
Bug tracker em400 na pewno nie jest odpowiednim miejscem na te kwestie.
Poprawki i ulepszenia dokumentacji EMAS-a proszę zgłaszać tutaj: https://github.com/jakubfi/emas/issues/2

**Comment by wir19** [comment]
Odsyłasz do wątku na bug tracker i jednoczesnie nie chcesz by pisac na bug track?

Faktycznie nie ma jakiegoś innego sposobu by się z Toba skontaktować. Na wiki nie widziałem sposobu. Może jakieś IRC?

**Comment by jakubfi** [comment]
em400 to emulator MERY-400. Problemy i których piszesz, dotyczą emas-a, assemblera dla MERY-400, dlatego odesłałem do tamtego repozytorium. To ułatwia organizację pracy.

**Comment by wir19** [comment]
Pytanie (nie moje wiec to nie ja piszę) dotyczy wiki projektu mera i jak rozumiem emulatora.
A że ułatwia prace to fakt
