### ISSUE TITLE
Trudna kompilacja

### ISSUE THREAD

**Issue by wir19** [jakubfi/em400#17]
Aby zainstalować emulator musze mieć :
libemdas libemcrk ...
ale aby zainstalować libemdas musze mieć emelf ...

Może warto rozważyć po prostu subrepozytoria git lub jakiś sposób na zautomatyzowanie tego procesu?
P.S. Nie wszyscy mają cmake można by było zrobic zwykłe makefile

**Comment by jakubfi** [comment]
Automatyzację procesu dostarczyć powinny paczki dla systemów i dystrybucji.
Kompilacja ręczna opisana jest tutaj: https://mera400.pl/EM400_-_Instalacja#R%C4%99czna_instalacja_ze_%C5%BAr%C3%B3de%C5%82

**Comment by wir19** [comment]
Ja sugeruję tylko by ujednolicić, zautomatyzowac biblioteki skoro jest już git
i poinformowac w readme bo na razie jest informacja, ze potrzebne sa biblioteki ale nie wiadomo gdzie one są ;-)

**Comment by wir19** [comment]
hallo, może jednak poprawisz dokumentacje do kompilacji?

**Comment by jakubfi** [comment]
> hallo, może jednak poprawisz dokumentacje do kompilacji?

Dokumentacja kompilacji dostępna pod adresem https://mera400.pl/EM400_-_Instalacja#R%C4%99czna_instalacja_ze_%C5%BAr%C3%B3de%C5%82 została przetestowana - jest aktualna i poprawna, również jeśli chodzi o kolejność kompilacji.

**Comment by sunwire** [comment]
@wir19 Jeżeli używasz Fedory (34 lub 35) to możesz użyć mojego repa na COPRze https://copr.fedorainfracloud.org/coprs/sunwire/MERA-400/
Dla starszych wersji będziesz musiał sam sobie skompilować.
Kolejność ręcznej kompilacji to:
emawp
emcrk
emelf
emdas
emas
emlin
em400
assem

**Comment by jakubfi** [comment]
@sunwire Dzięki za przygotowanie paczek dla Fedory. :-) Czy miałbyś coś przeciwko, żebym dodał https://copr.fedorainfracloud.org/coprs/sunwire/MERA-400/ do https://mera400.pl/EM400_-_Instalacja ?

I jeszcze jedno: W podanej przez Ciebie kolejności kompilacji, względem tego, co jest na mera400.pl, zamieniłeś "em400 emas emlin" na "emas emlin em400". Ponieważ ta trójka ma i tak spełnione już wszystkie wcześniejsze zależności, to kolejność nie powinna mieć tutaj znaczenia. Ciekaw jestem, czy dla Fedory z jakiegoś powodu taka zmiana jest konieczna?

**Comment by sunwire** [comment]
@jakubfi Oczywiście śmiało możesz dodać.
Myślę, że zmiana w kolejności nie ma żadnego znaczenia dla Fedory, po prostu ja skompilowałem w takiej kolejności :)

**Comment by jakubfi** [comment]
A zatem dodane, jeszcze raz dzięki!

**Comment by wir19** [comment]
Czy paczki będą obecne w głównym drzewie? Na razie nie widac ich w systemie.
po drugie troszke mało plików.
jak zauwazyles kwestia .ini
po drugie brak e4term co jest minimalnym wymaganiem do uruchomienia czegokolwiek (inne toolsy chyba mozna pominac)

zatem do czasu dopisania trybu wsadowego taka paczka jest nieuzyteczna.

**Comment by sunwire** [comment]
@wir19 
Paczki raczej nie będą w głównym drzewie.
Co masz na myśli mówiąc mało plików?
e4term jest dostępny w pakiecie em400.
Może napisze dokładnie jak zainstalować w Fedorze 34/35
W konsoli jako root wydajesz polecenia:
```
dnf copr enable sunwire/MERA-400 -y
dnf install em400 -y
```
Już jako zwykły użytkownik, musisz skopiować przykładowy plik konfiguracyjny do swojego katalogu domowego poleceniem
`cp /usr/share/em400/cfg/mera400.ini ~/.em400/em400.ini`
I to wszystko.

**Comment by wir19** [comment]
Nie wiem dlaczego miały by nie być w głównym drzewie?
Hm.... może mam jakąs starą wersję , mówimy o /usr/bin/ ?
wersja fedora 35?

co do .ini to ja używam ze strony

```
[cpu]
fpga = false
speed_real = false
speed_factor = 1
throttle_granularity = 10

clock_period = 10
clock_start = true

stop_on_nomem = false
user_io_illegal = false
awp = true
modifications = true
kb = 0

[memory]
elwro_modules = 1
mega_modules = 16
hardwired_segments = 2
mega_prom = mega0.bin
mega_boot = true
#preload =

[log]
enabled = false
file = em400.log
components = em4h
line_buffered = true

[ui]
interface = curses

[sound]
enabled = false
driver = alsa
output = default
rate = 48000
buffer_len = 128
latency = 20
volume = 30
filter = true

[fpga]
device = /dev/ttyUSB1
speed = 1000000

[io]
channel_1 = multix
channel_15 = char

[dev1.0]
type = puncher

[dev1.1]
type = puncher

[dev1.2]
type = puncher

[dev1.3]
type = punchreader

[dev1.4]
type = terminal
transport = tcp
port = 32004

[dev1.5]
type = terminal
transport = tcp
port = 32005

[dev1.6]
type = terminal
transport = tcp
port = 32006

[dev1.7]
type = terminal
transport = tcp
port = 32007

[dev1.8]
type = terminal
transport = tcp
port = 32008

[dev1.9]
type = terminal
transport = tcp
port = 32009

[dev1.10]
type = terminal
transport = tcp
port = 32010

[dev1.11]
type = terminal
transport = tcp
port = 32011

[dev1.12]
type = terminal
transport = tcp
port = 32012

[dev1.13]
type = terminal
transport = tcp
port = 32013

[dev1.14]
type = terminal
transport = tcp
port = 32014

[dev1.15]
type = terminal
transport = tcp
port = 32015

[dev1.28]
type = winchester
image = crook5-p8f-1.1.0.e4i

[dev15.4]
type = terminal
transport = tcp
port = 32000
speed = 9600
```

**Comment by wir19** [comment]
warto też było by dodac linki do systemu operacyjnego i dysku. nie kazdy może od razu wiedzieć gdzie szukać.
nie każdy pewnie będzie potrzebować ale warto dac info.

Zreszta jeśli autor by się zgodzil to mozna zrobic druga paczkę z tymi plikami.
