### ISSUE TITLE
jak utworzyć użytkownika i czy terminal jest konieczny

### ISSUE THREAD

**Issue by wir19** [jakubfi/em400#19]
W jaki sposób utworzyć użytkownika? Innego niż '**boss**'

Dlaczego terminal nie jest po prostu wbudowany w emulator? Nie każdy komputer ma wielozadaniowy system.

Dobrze by było tez ustawić domyślny tryb przyjmowania poleceń. Nie wiem czy każdy potrzebuje konsoli komputera. 
Czy sekcja [asm] nie spowalnia pracy komputera?

**Comment by jakubfi** [comment]
> W jaki sposób utworzyć użytkownika? Innego niż '**boss**'

Pytanie nie dotyczy emulatora em400 a systemu operacyjnego CROOK-5. Dokumentacja tutaj: https://mera400.pl/System_Operacyjny_CROOK-5

> Dlaczego terminal nie jest po prostu wbudowany w emulator? Nie każdy komputer ma wielozadaniowy system.

Decyzja architektoniczna - takie rozwiązanie jest bardziej elastyczne i "w duchu" tego, jak kompletowany był system MERA-400.

> Dobrze by było tez ustawić domyślny tryb przyjmowania poleceń. Nie wiem czy każdy potrzebuje konsoli komputera. Czy sekcja [asm] nie spowalnia pracy komputera?

Spowalnia pracę emulatora.

**Comment by wir19** [comment]
czy zatem można wyłączyć sekcje [asm] nie wiedzialem w opcjach by była taka możliwosc

**Comment by jakubfi** [comment]
> czy zatem można wyłączyć sekcje [asm] nie wiedzialem w opcjach by była taka możliwosc

W interfejsie użytkownika "curses" emulatora em400 nie ma możliwości wyłączenia deassemblacji pokazywanej w oknie "ASM". Jest ona kluczowa dla funkcjonalności tego sposobu pracy z emulatorem.

**Comment by wir19** [comment]
to swietna okazja by ja dodac ;-)
