### ISSUE TITLE
tryb wsadowy

### ISSUE THREAD

**Issue by wir19** [jakubfi/em400#20]
Zawsze był tryb wsadowy. Po prostu przynosiło się kilogram kart i na drugi dzień dostawałes wydruk. 
Świetny sposób na zrobienie profilera i benchmarki. 

Pytanie brzmi, jak uruchomic program który wypisuje jakies dane?

Czy każdy program, który napiszemy może działac bez systemu operacyjnego?

**Comment by jakubfi** [comment]
> Pytanie brzmi, jak uruchomic program który wypisuje jakies dane?

Program, który miałby komunikować się z użytkownikiem, musiałby zostać uruchomiony w emulatorze ze skonfigurowanym przynajmniej jednym urządzeniem zewnętrznym - terminalem.

> Czy każdy program, który napiszemy może działac bez systemu operacyjnego?

To zależy wyłącznie od tego, czy program jest napisany tak, aby działał z jakimś systemem operacyjnym, czy tak, aby działał bez kontroli żadnego systemu operacyjnego.

**Comment by wir19** [comment]
>>    Pytanie brzmi, jak uruchomic program który wypisuje jakies dane?

>Program, który miałby komunikować się z użytkownikiem, musiałby zostać uruchomiony w emulatorze ze 
>skonfigurowanym przynajmniej jednym urządzeniem zewnętrznym - terminalem.

Właśnie o tym pisę ;-) chodzi o to by dodać taką funkcjonalność. Aby właśnie móc zrobić benchmark, testy czy nawet zrobic obliczenia bez konsoli. Taka opcja pozwoliła by też na uruchamianie programów przez WWW w przyszłości.

>    Czy każdy program, który napiszemy może działac bez systemu operacyjnego?

>To zależy wyłącznie od tego, czy program jest napisany tak, aby działał z jakimś systemem operacyjnym, czy 
>tak, aby działał bez kontroli żadnego systemu operacyjnego.

A można prosić o taki przykład? Konkretny program, który będzie działac bez systemu operacyjnego.
Jak go uruchomić itd.

**Comment by wir19** [comment]
Napisz te dwie linijki z informacją jak uruchomić jakikolwiek przykład.
Cos realnego, konkretnego, niezależnego od systemu.
Po prostu piszemy, kompilujemy, uruchamiamy i coś działa
COKOLWIEK!

**Comment by jakubfi** [comment]
Uruchomienie przykładowych programów z repozytorium emas-a zostało opisane [tutal](https://mera400.pl/EM400_-_uruchamianie_program%C3%B3w).

**Comment by wir19** [comment]
Dziękuję za informacje z wiki. Proponuję dodać jeszcze wczytywanie danych z klawiatury. Aby był pełen obraz, wyświetlanie, wczytywanie i przetwarzanie.
Tak jak pisałem wcześniej warto zrobić jeszcze jeden tryb, w którym wszystkie te elementy będą razem. Może niech będzie to odrebny program, w którym .ini tylko tryb wsadowy i wszystko będzie działać od razu. Nawet jeśli miało by to obsługiwac tylko jeden program.
