### ISSUE TITLE
plany

### ISSUE THREAD

**Issue by texrg** [jakubfi/em400#22]
Brakuje mi planów elektronicznych, jakie procesory były używane i jak sa połączone.
Właściwie nie da sie odtworzyć płytek drukowanych samodzielnie. Albo zrobić bez układów scalonych, na samych tranzystorach.

**Comment by sunwire** [comment]
Wszystkie schematy i dane masz [tutaj](https://mera400.pl/Literatura) w szczególności Dokumentacja Techniczno-Ruchowa

**Comment by jakubfi** [comment]
Dzięki @sunwire ;-)
Raport nie związany z em400, zamykam.
