### ISSUE TITLE
java

### ISSUE THREAD

**Issue by xor256** [jakubfi/em400#23]
Znalazłem taki projekt https://sourceforge.net/projects/vm02/
ciekawe czy przeniesienie lua lub javy wymagało by dużego nakładu pracy.

**Comment by jakubfi** [comment]
Nie bardzo rozumiem jaki miałby być spodziewany rezultat w kontekście EM400.
Czy mógłbyś wyjaśnić co chciałbyś osiągnąć?

**Comment by jakubfi** [comment]
Brak odpowiedzi od raportującego.
